#cloud-config

users:
    - name: dev
    ssh-authorized-keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmaqbeev+B54vgppVTV5qBpp5nMz+V8Qh99KTIXWmfSDQmn1isysZFzdz6SkQLQ8O92KdLfHDhM6UydpuPAqukODPO4S5J2TvH+VTGM5Ewu2mhevjaNn11RI35uPtC7G97sqoBG8LaZi98/g0avi21CSp7JJ1r/fHePzbWVy7yQns5lgI33WgsXmHHwuPYwutTCLiJ96aAq0XiTXI/zvMhBri3tQ7ODjOzmex14PT4yngnk9UTLn+AjIn1jP0l0p4RzbDj5d25Rb3MR5TaOww0bPxVdqxb0go+iTvxWsohmwSKqkQzoz9pZOYrUymIUMbc6rSCnrD5vsV2hSGsHUOp
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

packages:
    - mysql-client
    - libmysqlclient-dev
    - mysql-server

package_update: true
package_upgrade: true

runcmd:

#
# SSH
#
    - sed -i -e '/^Port/s/^.*$/Port 22/' /etc/ssh/sshd_config
    - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
    - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
    - sed -i -e '$aAllowUsers dev' /etc/ssh/sshd_config

    - sudo service ssh restart

#
# Firewall
#

    # defaults
    - sudo ufw default deny incoming
    - sudo ufw default allow outgoing

    # exceptions
    - sudo ufw allow ssh
    - sudo ufw allow http
    - sudo ufw allow https

    # start on boot
    - sed -i -e '/^ENABLED/s/^.*$/ENABLED=yes/' /etc/ufw/ufw.conf

    - sudo ufw enable