- hosts: localhost
  become: yes
  become_method: sudo
  tasks:    
    - name: pip install setuptools
      pip: name=setuptools

    - name: pip install wheel
      pip: name=wheel
    
    - name: pip install docker-py
      pip: name=docker-py

    - name: Create a mysql container
      docker_container:
        name: mysqlcontainer
        image: mysql:5.7
        restart_policy: always
        env:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

#docker.io en version want anders fout dat hij api ni kan vinden pip shit omdat hij ook zegt da hij anders niks wilt doen