#cloud-config
packages:
  - pwgen
  - git
  - tree
package_upgrade: true
runcmd:
  - mkdir /home/bachelorproef/onderzoek/fotos -p
  - mkdir /home/bachelorproef/onderzoek/teksten -p
  - mkdir /home/bachelorproef/presentatiebestanden -p
  - mkdir /home/stage/presentatiebestanden -p
  - mkdir /home/stage/veslagbestanden -p
groups:
  - test
users:
  - default
  - name: bachelor
  - passwd: 985b56433efe9898290b88d4dab853a2f09d7eb7a7b1b8d2cdd431e2920c3586abb7f15af7ef5382fc07d47f37b9dd4d68535b9328a07a2fccd828385c70ddc2
  - sudo: true
  - groups: test
  - shell: /bin/bash
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmaqbeev+B54vgppVTV5qBpp5nMz+V8Qh99KTIXWmfSDQmn1isysZFzdz6SkQLQ8O92KdLfHDhM6UydpuPAqukODPO4S5J2TvH+VTGM5Ewu2mhevjaNn11RI35uPtC7G97sqoBG8LaZi98/g0avi21CSp7JJ1r/fHePzbWVy7yQns5lgI33WgsXmHHwuPYwutTCLiJ96aAq0XiTXI/zvMhBri3tQ7ODjOzmex14PT4yngnk9UTLn+AjIn1jP0l0p4RzbDj5d25Rb3MR5TaOww0bPxVdqxb0go+iTvxWsohmwSKqkQzoz9pZOYrUymIUMbc6rSCnrD5vsV2hSGsHUOp 
final_message: "The system is finally up, after $UPTIME seconds"