- hosts: localhost
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
    - name: Install git
      apt:
        name: git
        state: present
    - name: Install tree
      apt:
        name: tree
        state: present
    - name: Install pwgen
      apt:
        name: pwgen
        state: present
    - name: Set authorized key taken from file
      authorized_key:
        user: charlie
        state: present
        key: "{{ lookup('file', '/vagrant/key') }}"
    - name: Creates direcory fotos
      file:
        path: /home/bachelorproef/onderzoek/fotos
        state: directory
    - name: Creates direcory teksten
      file:
        path: /home/bachelorproef/onderzoek/teksten
        state: directory
    - name: Creates direcory stage presentatie
      file:
        path: /home/bachelorproef/presentatiebestanden
        state: directory
    - name: Creates direcory bachelor presentatie
      file:
        path: /home/stage/presentatiebestanden
        state: directory
    - name: Creates direcory stage verslag
      file:
        path: /home/bachelorproef/stage/verslagbestanden
        state: directory
    - name:  add group test
      group:
        name: test
        state: present
    - name:  add user bachelor
      user:
        name: bachelor
        groups: test,admin
        shell: /bin/bash
        password: 985b56433efe9898290b88d4dab853a2f09d7eb7a7b1b8d2cdd431e2920c3586abb7f15af7ef5382fc07d47f37b9dd4d68535b9328a07a2fccd828385c70ddc2985b56433efe9898290b88d4dab853a2f09d7eb7a7b1b8d2cdd431e2920c3586abb7f15af7ef5382fc07d47f37b9dd4d68535b9328a07a2fccd828385c70ddc2
